In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
# 単純なアレイを用意します。
arr1 = np.arange(9).reshape((3,3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
# 2つのアレイを列方向（axis=1）に連結します
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
# 行方向（axis=0）に
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# pandas.Seriesでやってみます。
ser1 =  Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [8]:
ser1

T    0
U    1
V    2
dtype: int64

In [9]:
ser2

X    3
Y    4
dtype: int64

In [12]:
# concatで、デフォルトは axis=0
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [13]:
pd.concat([ser1,ser2,ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [15]:
# 列方向に連結すると、DataFrameが出来ます。
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [16]:
# 階層的なindexを付けてSeriesを連結することもできます。
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [17]:
# 列方向に連結すると、列の名前になります。
pd.concat([ser1,ser2],axis=1,keys=['cat1','cat2'])

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [18]:
# DataFrameでも同じ事ができます。
dframe1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])
dframe2 = DataFrame(np.random.randn(3, 3), columns=['Y', 'Q', 'X'])

In [19]:
dframe1

X         Y         Z
0 -1.172156  1.857409 -1.781829
1 -0.509969 -1.670733 -1.932412
2 -0.156396 -0.588426 -0.006798
3 -0.625469 -0.233703  0.943980

In [20]:
dframe2

Y         Q         X
0  0.560455 -1.341676 -0.484018
1  0.950753 -0.972896 -0.110138
2  0.858754  0.766568 -1.173375

In [21]:
# DataFrameを連結します。
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -1.172156  1.857409 -1.781829
1       NaN -0.509969 -1.670733 -1.932412
2       NaN -0.156396 -0.588426 -0.006798
3       NaN -0.625469 -0.233703  0.943980
0 -1.341676 -0.484018  0.560455       NaN
1 -0.972896 -0.110138  0.950753       NaN
2  0.766568 -1.173375  0.858754       NaN

In [22]:
# もとのindexを無視することもできます。
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN -1.172156  1.857409 -1.781829
1       NaN -0.509969 -1.670733 -1.932412
2       NaN -0.156396 -0.588426 -0.006798
3       NaN -0.625469 -0.233703  0.943980
4 -1.341676 -0.484018  0.560455       NaN
5 -0.972896 -0.110138  0.950753       NaN
6  0.766568 -1.173375  0.858754       NaN

In [24]:
# We can specify which specific axes to be used
pd.concat([ser1,ser2],axis=1,join_axes=[['U','V','Y']])

0    1
U  1.0  NaN
V  2.0  NaN
Y  NaN  4.0